/*
        Class:          AccountTriggerHandler
        @Author:        Ram Bonala
        @Created Date:  17/4/2021
        @Description:   handler class for Account triggers

    Change History
******************************************************************
    ModifiedBy          Date        Requested By        Description                 Tag
    
******************************************************************
*/

Public Class AccountTriggerHandler{

    
    public static String getPhone() {
        return 'SamplePhone#';
    }
    
    public static void helloMethod() {
        System.debug('Hello World');
    }
    

  }